export const words: Record<string, string[]> = {
  animales: [
    "perro",
    "gato",
    "elefante",
    "jirafa",
    "leon",
    "tigre",
    "oso",
    "lobo",
    "zorro",
    "conejo",
    "caballo",
    "vaca",
    "cerdo",
    "gallina",
    "pato",
    "aguila",
    "buho",
    "serpiente",
    "cocodrilo",
    "tiburon",
    "delfin",
    "ballena",
    "pulpo",
    "cangrejo",
    "tortuga",
    "rana",
    "mariposa",
    "abeja",
    "hormiga",
    "araña",
  ],
  comida: [
    "pizza",
    "hamburguesa",
    "tacos",
    "sushi",
    "pasta",
    "ensalada",
    "sopa",
    "arroz",
    "pollo",
    "pescado",
    "helado",
    "chocolate",
    "pastel",
    "galleta",
    "pan",
    "queso",
    "huevo",
    "manzana",
    "banana",
    "naranja",
    "fresa",
    "sandia",
    "uva",
    "limon",
    "papas fritas",
    "hotdog",
    "sandwich",
    "burrito",
    "nachos",
    "palomitas",
  ],
  peliculas: [
    "Titanic",
    "Matrix",
    "Avatar",
    "Inception",
    "Gladiator",
    "Shrek",
    "Frozen",
    "Coco",
    "Up",
    "Ratatouille",
    "Toy Story",
    "Buscando a Nemo",
    "El Rey Leon",
    "Aladdin",
    "Mulan",
    "Jurassic Park",
    "Star Wars",
    "Harry Potter",
    "El Señor de los Anillos",
    "Batman",
    "Spider-Man",
    "Iron Man",
    "Avengers",
    "Joker",
    "Forrest Gump",
    "El Padrino",
    "Volver al Futuro",
    "E.T.",
    "Tiburon",
    "Rocky",
  ],
  lugares: [
    "playa",
    "montaña",
    "bosque",
    "desierto",
    "isla",
    "rio",
    "lago",
    "cascada",
    "volcan",
    "cueva",
    "hospital",
    "escuela",
    "universidad",
    "biblioteca",
    "museo",
    "parque",
    "estadio",
    "cine",
    "teatro",
    "restaurante",
    "supermercado",
    "aeropuerto",
    "estacion de tren",
    "hotel",
    "iglesia",
    "castillo",
    "piramide",
    "torre",
    "puente",
    "faro",
  ],
  deportes: [
    "futbol",
    "basketball",
    "tenis",
    "golf",
    "natacion",
    "atletismo",
    "ciclismo",
    "boxeo",
    "lucha libre",
    "karate",
    "judo",
    "taekwondo",
    "esgrima",
    "gimnasia",
    "patinaje",
    "ski",
    "snowboard",
    "surf",
    "skateboard",
    "beisbol",
    "volleyball",
    "rugby",
    "hockey",
    "ping pong",
    "badminton",
    "polo",
    "equitacion",
    "escalada",
    "parkour",
    "crossfit",
  ],
  profesiones: [
    "medico",
    "enfermera",
    "bombero",
    "policia",
    "profesor",
    "abogado",
    "ingeniero",
    "arquitecto",
    "chef",
    "mesero",
    "piloto",
    "astronauta",
    "actor",
    "cantante",
    "musico",
    "pintor",
    "escritor",
    "fotografo",
    "periodista",
    "veterinario",
    "dentista",
    "psicologo",
    "mecanico",
    "electricista",
    "carpintero",
    "plomero",
    "jardinero",
    "peluquero",
    "sastre",
    "panadero",
  ],
};

export const categories = Object.keys(words);
