export interface WordWithTaboo {
  word: string;
  taboo: string[];
}

export const words: Record<string, WordWithTaboo[]> = {
  animales: [
    { word: "perro", taboo: ["ladrar", "mascota", "canino"] },
    { word: "gato", taboo: ["maullar", "felino", "bigotes"] },
    { word: "elefante", taboo: ["trompa", "grande", "colmillos"] },
    { word: "jirafa", taboo: ["cuello", "alto", "manchas"] },
    { word: "leon", taboo: ["melena", "rey", "rugir"] },
    { word: "tigre", taboo: ["rayas", "selva", "felino"] },
    { word: "oso", taboo: ["hibernar", "garras", "peluche"] },
    { word: "lobo", taboo: ["aullar", "manada", "luna"] },
    { word: "zorro", taboo: ["astuto", "naranja", "cola"] },
    { word: "conejo", taboo: ["orejas", "zanahoria", "saltar"] },
    { word: "caballo", taboo: ["montar", "galope", "establo"] },
    { word: "vaca", taboo: ["leche", "mugir", "granja"] },
    { word: "cerdo", taboo: ["rosa", "granja", "barro"] },
    { word: "gallina", taboo: ["huevo", "cacarear", "plumas"] },
    { word: "pato", taboo: ["cuac", "nadar", "pico"] },
    { word: "aguila", taboo: ["volar", "garras", "pico"] },
    { word: "buho", taboo: ["nocturno", "sabio", "ojos"] },
    { word: "serpiente", taboo: ["veneno", "escamas", "sisear"] },
    { word: "cocodrilo", taboo: ["pantano", "dientes", "reptil"] },
    { word: "tiburon", taboo: ["aleta", "dientes", "oceano"] },
    { word: "delfin", taboo: ["inteligente", "nadar", "saltar"] },
    { word: "ballena", taboo: ["gigante", "oceano", "chorro"] },
    { word: "pulpo", taboo: ["tentaculos", "tinta", "ocho"] },
    { word: "cangrejo", taboo: ["pinzas", "playa", "caminar"] },
    { word: "tortuga", taboo: ["caparazon", "lenta", "reptil"] },
    { word: "rana", taboo: ["saltar", "verde", "croar"] },
    { word: "mariposa", taboo: ["alas", "colores", "oruga"] },
    { word: "abeja", taboo: ["miel", "picar", "colmena"] },
    { word: "hormiga", taboo: ["colonia", "pequena", "trabajadora"] },
    { word: "arana", taboo: ["tela", "patas", "ocho"] },
  ],
  comida: [
    { word: "pizza", taboo: ["italia", "queso", "redonda"] },
    { word: "hamburguesa", taboo: ["carne", "pan", "mcdonalds"] },
    { word: "tacos", taboo: ["mexico", "tortilla", "carne"] },
    { word: "sushi", taboo: ["japon", "arroz", "pescado"] },
    { word: "pasta", taboo: ["italia", "fideos", "salsa"] },
    { word: "ensalada", taboo: ["lechuga", "saludable", "verde"] },
    { word: "sopa", taboo: ["caliente", "cuchara", "liquido"] },
    { word: "arroz", taboo: ["blanco", "grano", "asia"] },
    { word: "pollo", taboo: ["ave", "carne", "frito"] },
    { word: "pescado", taboo: ["mar", "escamas", "nadar"] },
    { word: "helado", taboo: ["frio", "dulce", "cucurucho"] },
    { word: "chocolate", taboo: ["dulce", "cacao", "marron"] },
    { word: "pastel", taboo: ["cumpleanos", "dulce", "velas"] },
    { word: "galleta", taboo: ["crujiente", "dulce", "hornear"] },
    { word: "pan", taboo: ["harina", "hornear", "panaderia"] },
    { word: "queso", taboo: ["leche", "amarillo", "raton"] },
    { word: "huevo", taboo: ["gallina", "frito", "cascara"] },
    { word: "manzana", taboo: ["roja", "fruta", "arbol"] },
    { word: "banana", taboo: ["amarilla", "mono", "cascara"] },
    { word: "naranja", taboo: ["citrico", "jugo", "vitamina"] },
    { word: "fresa", taboo: ["roja", "dulce", "pequena"] },
    { word: "sandia", taboo: ["verde", "semillas", "verano"] },
    { word: "uva", taboo: ["vino", "racimo", "morada"] },
    { word: "limon", taboo: ["acido", "amarillo", "citrico"] },
    { word: "papas fritas", taboo: ["sal", "crujiente", "aceite"] },
    { word: "hotdog", taboo: ["salchicha", "pan", "mostaza"] },
    { word: "sandwich", taboo: ["pan", "jamon", "queso"] },
    { word: "burrito", taboo: ["mexico", "enrollado", "tortilla"] },
    { word: "nachos", taboo: ["tortilla", "queso", "mexico"] },
    { word: "palomitas", taboo: ["maiz", "cine", "sal"] },
  ],
  peliculas: [
    { word: "Titanic", taboo: ["barco", "hundirse", "rose"] },
    { word: "Matrix", taboo: ["neo", "pastilla", "realidad"] },
    { word: "Avatar", taboo: ["azul", "pandora", "alien"] },
    { word: "Inception", taboo: ["sueno", "trompo", "capas"] },
    { word: "Gladiator", taboo: ["roma", "arena", "maximus"] },
    { word: "Shrek", taboo: ["ogro", "verde", "burro"] },
    { word: "Frozen", taboo: ["elsa", "hielo", "cancion"] },
    { word: "Coco", taboo: ["mexico", "muertos", "guitarra"] },
    { word: "Up", taboo: ["globos", "casa", "volar"] },
    { word: "Ratatouille", taboo: ["rata", "cocina", "paris"] },
    { word: "Toy Story", taboo: ["woody", "buzz", "juguetes"] },
    { word: "Buscando a Nemo", taboo: ["pez", "payaso", "oceano"] },
    { word: "El Rey Leon", taboo: ["simba", "africa", "mufasa"] },
    { word: "Aladdin", taboo: ["genio", "lampara", "alfombra"] },
    { word: "Mulan", taboo: ["china", "dragon", "guerrera"] },
    { word: "Jurassic Park", taboo: ["dinosaurios", "isla", "trex"] },
    { word: "Star Wars", taboo: ["espada", "vader", "fuerza"] },
    { word: "Harry Potter", taboo: ["magia", "hogwarts", "varita"] },
    { word: "El Senor de los Anillos", taboo: ["frodo", "anillo", "hobbit"] },
    { word: "Batman", taboo: ["murcielago", "gotham", "alfred"] },
    { word: "Spider-Man", taboo: ["arana", "telarana", "peter"] },
    { word: "Iron Man", taboo: ["stark", "armadura", "reactor"] },
    { word: "Avengers", taboo: ["heroes", "thanos", "marvel"] },
    { word: "Joker", taboo: ["payaso", "batman", "gotham"] },
    { word: "Forrest Gump", taboo: ["correr", "chocolates", "pluma"] },
    { word: "El Padrino", taboo: ["mafia", "corleone", "oferta"] },
    { word: "Volver al Futuro", taboo: ["delorean", "tiempo", "marty"] },
    { word: "E.T.", taboo: ["alien", "bicicleta", "telefono"] },
    { word: "Tiburon", taboo: ["playa", "dientes", "musica"] },
    { word: "Rocky", taboo: ["boxeo", "filadelfia", "adrian"] },
  ],
  lugares: [
    { word: "playa", taboo: ["arena", "mar", "sol"] },
    { word: "montana", taboo: ["alto", "escalar", "nieve"] },
    { word: "bosque", taboo: ["arboles", "verde", "naturaleza"] },
    { word: "desierto", taboo: ["arena", "calor", "seco"] },
    { word: "isla", taboo: ["agua", "palmera", "tropical"] },
    { word: "rio", taboo: ["agua", "corriente", "peces"] },
    { word: "lago", taboo: ["agua", "quieto", "nadar"] },
    { word: "cascada", taboo: ["agua", "caer", "rocas"] },
    { word: "volcan", taboo: ["lava", "erupcion", "crater"] },
    { word: "cueva", taboo: ["oscuro", "roca", "murcielago"] },
    { word: "hospital", taboo: ["doctor", "enfermo", "cama"] },
    { word: "escuela", taboo: ["estudiante", "profesor", "clase"] },
    { word: "universidad", taboo: ["estudiante", "carrera", "campus"] },
    { word: "biblioteca", taboo: ["libros", "silencio", "leer"] },
    { word: "museo", taboo: ["arte", "historia", "cuadros"] },
    { word: "parque", taboo: ["arboles", "juegos", "verde"] },
    { word: "estadio", taboo: ["futbol", "gradas", "partido"] },
    { word: "cine", taboo: ["pelicula", "palomitas", "pantalla"] },
    { word: "teatro", taboo: ["obra", "actores", "escenario"] },
    { word: "restaurante", taboo: ["comida", "mesero", "menu"] },
    { word: "supermercado", taboo: ["compras", "carrito", "productos"] },
    { word: "aeropuerto", taboo: ["avion", "viajar", "maleta"] },
    { word: "estacion de tren", taboo: ["tren", "vias", "andén"] },
    { word: "hotel", taboo: ["habitacion", "dormir", "vacaciones"] },
    { word: "iglesia", taboo: ["religion", "misa", "cruz"] },
    { word: "castillo", taboo: ["rey", "torre", "medieval"] },
    { word: "piramide", taboo: ["egipto", "faraon", "triangulo"] },
    { word: "torre", taboo: ["alto", "edificio", "eiffel"] },
    { word: "puente", taboo: ["cruzar", "rio", "estructura"] },
    { word: "faro", taboo: ["luz", "mar", "barco"] },
  ],
  deportes: [
    { word: "futbol", taboo: ["pelota", "gol", "cancha"] },
    { word: "basketball", taboo: ["canasta", "pelota", "aro"] },
    { word: "tenis", taboo: ["raqueta", "pelota", "red"] },
    { word: "golf", taboo: ["palo", "hoyo", "pelota"] },
    { word: "natacion", taboo: ["agua", "piscina", "nadar"] },
    { word: "atletismo", taboo: ["correr", "pista", "medalla"] },
    { word: "ciclismo", taboo: ["bicicleta", "pedal", "tour"] },
    { word: "boxeo", taboo: ["guantes", "ring", "golpe"] },
    { word: "lucha libre", taboo: ["mascara", "ring", "llave"] },
    { word: "karate", taboo: ["cinturon", "patada", "dojo"] },
    { word: "judo", taboo: ["llave", "tatami", "japon"] },
    { word: "taekwondo", taboo: ["patada", "corea", "cinturon"] },
    { word: "esgrima", taboo: ["espada", "mascara", "tocar"] },
    { word: "gimnasia", taboo: ["voltereta", "colchoneta", "flexible"] },
    { word: "patinaje", taboo: ["hielo", "patines", "pirueta"] },
    { word: "ski", taboo: ["nieve", "montana", "bajar"] },
    { word: "snowboard", taboo: ["nieve", "tabla", "montana"] },
    { word: "surf", taboo: ["ola", "tabla", "playa"] },
    { word: "skateboard", taboo: ["tabla", "ruedas", "truco"] },
    { word: "beisbol", taboo: ["bate", "pelota", "base"] },
    { word: "volleyball", taboo: ["red", "pelota", "playa"] },
    { word: "rugby", taboo: ["pelota", "tackle", "ovalada"] },
    { word: "hockey", taboo: ["hielo", "puck", "palo"] },
    { word: "ping pong", taboo: ["paleta", "pelota", "mesa"] },
    { word: "badminton", taboo: ["pluma", "raqueta", "red"] },
    { word: "polo", taboo: ["caballo", "pelota", "palo"] },
    { word: "equitacion", taboo: ["caballo", "montar", "jinete"] },
    { word: "escalada", taboo: ["roca", "cuerda", "subir"] },
    { word: "parkour", taboo: ["saltar", "ciudad", "obstaculo"] },
    { word: "crossfit", taboo: ["gym", "intenso", "ejercicio"] },
  ],
  profesiones: [
    { word: "medico", taboo: ["hospital", "enfermo", "bata"] },
    { word: "enfermera", taboo: ["hospital", "inyeccion", "cuidar"] },
    { word: "bombero", taboo: ["fuego", "manguera", "rojo"] },
    { word: "policia", taboo: ["uniforme", "arrestar", "insignia"] },
    { word: "profesor", taboo: ["escuela", "ensenar", "clase"] },
    { word: "abogado", taboo: ["ley", "juicio", "cliente"] },
    { word: "ingeniero", taboo: ["construir", "planos", "calcular"] },
    { word: "arquitecto", taboo: ["edificio", "planos", "disenar"] },
    { word: "chef", taboo: ["cocina", "comida", "gorro"] },
    { word: "mesero", taboo: ["restaurante", "servir", "bandeja"] },
    { word: "piloto", taboo: ["avion", "volar", "cabina"] },
    { word: "astronauta", taboo: ["espacio", "cohete", "nasa"] },
    { word: "actor", taboo: ["pelicula", "actuar", "escena"] },
    { word: "cantante", taboo: ["musica", "cantar", "microfono"] },
    { word: "musico", taboo: ["instrumento", "tocar", "banda"] },
    { word: "pintor", taboo: ["cuadro", "brocha", "arte"] },
    { word: "escritor", taboo: ["libro", "escribir", "historia"] },
    { word: "fotografo", taboo: ["camara", "foto", "lente"] },
    { word: "periodista", taboo: ["noticias", "entrevista", "reportar"] },
    { word: "veterinario", taboo: ["animal", "mascota", "curar"] },
    { word: "dentista", taboo: ["dientes", "caries", "taladro"] },
    { word: "psicologo", taboo: ["mente", "terapia", "escuchar"] },
    { word: "mecanico", taboo: ["auto", "reparar", "motor"] },
    { word: "electricista", taboo: ["cables", "luz", "voltaje"] },
    { word: "carpintero", taboo: ["madera", "martillo", "mueble"] },
    { word: "plomero", taboo: ["tubo", "agua", "llave"] },
    { word: "jardinero", taboo: ["plantas", "cortar", "flores"] },
    { word: "peluquero", taboo: ["pelo", "cortar", "tijeras"] },
    { word: "sastre", taboo: ["ropa", "coser", "tela"] },
    { word: "panadero", taboo: ["pan", "hornear", "harina"] },
  ],
};

// Helper function to get just the word strings (for backward compatibility)
export function getWordStrings(category: string): string[] {
  const categoryWords = words[category as keyof typeof words];
  if (!categoryWords) return [];
  return categoryWords.map(w => w.word);
}

// Helper function to get a random word with its taboo words
export function getRandomWord(category: string): WordWithTaboo | null {
  const categoryWords = words[category as keyof typeof words];
  if (!categoryWords || categoryWords.length === 0) return null;
  return categoryWords[Math.floor(Math.random() * categoryWords.length)];
}

export const categories = Object.keys(words);
